# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojindo_backend', '0002_series'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='DojindoUsers',
        ),
    ]
