# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojindo_backend', '0005_auto_20160201_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_name', models.TextField()),
                ('volume_number', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='series_name',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='volume',
            name='parent_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojindo_backend.Collection'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dojindo_backend.User'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dojindo_backend.Volume'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='dojindo_backend.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='dojindo_backend.User'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojindo_backend.Collection'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojindo_backend.User'),
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.ManyToManyField(to='dojindo_backend.Category'),
        ),
    ]
