# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-01 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojindo_backend', '0012_auto_20160201_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='parent_series',
            new_name='collection',
        ),
    ]
