# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojindo_backend', '0013_auto_20160201_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceWork',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='series_name',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='author_user',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='volume_name',
        ),
        migrations.RemoveField(
            model_name='volume',
            name='volume_number',
        ),
        migrations.AddField(
            model_name='collection',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojindo_backend.User', to_field='name'),
        ),
        migrations.AddField(
            model_name='collection',
            name='cover_art',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='cover_art',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='volume',
            name='samplePage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='referenceWork',
            field=models.ManyToManyField(related_name='referenceWork', to='dojindo_backend.ReferenceWork'),
        ),
    ]
