# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojindo_backend', '0015_auto_20160204_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='name',
        ),
    ]
